// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvAOBqIYdq2lW9fNvaqKTxn3JJ1cSEc6E',
    appId: '1:345636954617:web:7c46ac745211dbd9de1d28',
    messagingSenderId: '345636954617',
    projectId: 'responsive-and-adaptive',
    authDomain: 'responsive-and-adaptive.firebaseapp.com',
    storageBucket: 'responsive-and-adaptive.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeHQgHgjLRR8Jux16aZrFMVePxJicog8o',
    appId: '1:345636954617:android:9a7cc376826fbd3bde1d28',
    messagingSenderId: '345636954617',
    projectId: 'responsive-and-adaptive',
    storageBucket: 'responsive-and-adaptive.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwCjIBfTpvmA5CIBfEC7tlRWeK0vyGBms',
    appId: '1:345636954617:ios:dcb3c3c26a7f9a29de1d28',
    messagingSenderId: '345636954617',
    projectId: 'responsive-and-adaptive',
    storageBucket: 'responsive-and-adaptive.firebasestorage.app',
    iosBundleId: 'com.example.responsiveAndAdaptiveDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwCjIBfTpvmA5CIBfEC7tlRWeK0vyGBms',
    appId: '1:345636954617:ios:dcb3c3c26a7f9a29de1d28',
    messagingSenderId: '345636954617',
    projectId: 'responsive-and-adaptive',
    storageBucket: 'responsive-and-adaptive.firebasestorage.app',
    iosBundleId: 'com.example.responsiveAndAdaptiveDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvAOBqIYdq2lW9fNvaqKTxn3JJ1cSEc6E',
    appId: '1:345636954617:web:ddd25281e6c49487de1d28',
    messagingSenderId: '345636954617',
    projectId: 'responsive-and-adaptive',
    authDomain: 'responsive-and-adaptive.firebaseapp.com',
    storageBucket: 'responsive-and-adaptive.firebasestorage.app',
  );

}