// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp7xePfeZBzvzvOhsMTtjRsdsL45lJOcA',
    appId: '1:435235654318:web:82764932b098a9e8eefb3f',
    messagingSenderId: '435235654318',
    projectId: 'new-app-note',
    authDomain: 'new-app-note.firebaseapp.com',
    storageBucket: 'new-app-note.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7bwYtfP7XcoUbKwHdkl_YOTciSBF4kbs',
    appId: '1:435235654318:android:c256c121f0e1d32ceefb3f',
    messagingSenderId: '435235654318',
    projectId: 'new-app-note',
    storageBucket: 'new-app-note.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXhJEizFAl1mTYuYgL2b-9v19rJZTGEV0',
    appId: '1:435235654318:ios:f397f7b9add05ba5eefb3f',
    messagingSenderId: '435235654318',
    projectId: 'new-app-note',
    storageBucket: 'new-app-note.appspot.com',
    iosBundleId: 'com.example.responsiveAndAdaptiveDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXhJEizFAl1mTYuYgL2b-9v19rJZTGEV0',
    appId: '1:435235654318:ios:f397f7b9add05ba5eefb3f',
    messagingSenderId: '435235654318',
    projectId: 'new-app-note',
    storageBucket: 'new-app-note.appspot.com',
    iosBundleId: 'com.example.responsiveAndAdaptiveDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAp7xePfeZBzvzvOhsMTtjRsdsL45lJOcA',
    appId: '1:435235654318:web:5b56b50cc419a618eefb3f',
    messagingSenderId: '435235654318',
    projectId: 'new-app-note',
    authDomain: 'new-app-note.firebaseapp.com',
    storageBucket: 'new-app-note.appspot.com',
  );

}